### ISSUE TITLE
create generator function

### ISSUE THREAD

**Issue by AnthonyRentsch** [AnthonyRentsch/AC297r_2019_somerville_parking#10]
inputs: directory path
outputs: yields images

**Comment by AnthonyRentsch** [comment]
One example: from our Data Science II final project: https://github.com/NicholasStern/E/blob/master/lipika/generator.py

**Comment by AnthonyRentsch** [comment]
https://github.com/NicholasStern/E/blob/master/final_milestone/memes_report_part2.ipynb

**Comment by JoshFeldman95** [comment]
I can do this!
